name: linting, testing, building
on:
  push:
    branches: [main, after-jest]
  pull_request:
    branches: [main]
jobs:
  pipeline:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./advanced-blog-pet
    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: install node modules
        uses: borales/actions-yarn@v4
        with:
          cmd: install # will run `yarn install` command
      - name: build production project
        uses: borales/actions-yarn@v4
        with:
          cmd: run build:prod
      - name: linting typescript, jsx, js
        uses: borales/actions-yarn@v4
        with:
          cmd: run eslint
      - name: linting scss
        uses: borales/actions-yarn@v4
        with:
          cmd: run stylelint
      - name: unit testing
        uses: borales/actions-yarn@v4
        with:
          cmd: run test:unit
