name: linting, testing, building
on:
  push:
    branches: [main, after-jest]
  pull_reauest:
    branches: [main]
jobs:
  pipeline:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - name: Check out repo's default branch
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm
      - name: install node modules
        run: npm ci
      - name: build broduction project
        run: npm run build:prod
      - name: tinting typescript, jsx, js
          run: npm run eslint
      - name: tinting scss
          run: npm run stylelint
       - name: unit testing
       run: npm run test:unit
